from setuptools import setup, find_packages

setup(name='safe_control_gym',
      version='2.0.0',
      packages=find_packages(include=['safe_control_gym*', 'gp*']),
      install_requires=[
          'matplotlib',
          'munch',
          'pyyaml',
          'imageio',
          'dict-deep',
          'scikit-optimize',
          'scikit-learn',
          'gymnasium',
          'torch',
          'gpytorch==1.13',
          'tensorboard',
          'casadi',
          'pybullet',
          'numpy',
          'scipy',
          'cvxpy',
          'cvxpygen',
          #'pycddlib',
          #'pytope',
          'Mosek',
          'clarabel',
          'termcolor',
          'pytest',
          'pre-commit',
          'pandas',
      ],
      )
